[package]
name = "server"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]
members = ["crates/*"]

[dependencies]
anyhow = "1.0.71"
async-mongodb-session = { version = "3.0.0", default-features = false }
async-session = "3.0.0"
axum = { version = "0.7.2", features = ["json"] }
axum-extra = { version = "0.9.0", features = ["cookie", "typed-header"] }
axum-server = "0.6.0"
base64 = "0.21.2"
bytes = "1.5.0"
chrono = "0.4.26"
clap = { version = "4.3.8", features = ["derive"] }
db = { path = "crates/db" }
dotenv = "0.15.0"
env_logger = "0.10.0"
extractor = { path = "crates/extractor" }
futures = "0.3.28"
http = "1.0.0"
log = "0.4.19"
model = { path = "crates/model" }
oauth2 = "4.4.1"
rayon = "1.7.0"
reqwest = { version = "0.11.23", default_features = false, features = [ "blocking", "json", "rustls-tls", ] }
rusoto_core = { version = "0.48.0", default_features = false, features = [ "rustls", ] }
rusoto_s3 = { version = "0.48.0", default_features = false, features = [ "rustls", ] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
sha2 = "0.10.7"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
tower = { version = "0.4.13", features = ["tracing", "limit", "buffer"] }
tower-http = { version = "0.5.0", features = ["cors", "fs", "trace"] }
tower_governor = "0.2.0"
tracing = "0.1.40"
typeshare = "1.0.2"
url = "2.4.0"
walkdir = "2.3.3"

[dev-dependencies]
hyper = { version = "1.1.0", features = ["server"] }
pretty_assertions = "1.3.0"
tempfile = "3.7.0"
tower = "0.4.13"
